version: '3.1'

services:
  postgres:
    image: postgres:15.5-alpine3.19
    container_name: postgres-local
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1212
